---
title: "Week12aHW"
author: "Chloe"
date: "2023-04-25"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, 
                      warning = FALSE)
```

```{r, forloop}
#Load Libraries 
library(here)
library(tidyverse)

#Code forloop
testhw<-read_csv(here("Week_12", "data", "homework", "TP1.csv"))
glimpse(testhw)

CondPath<-here("Week_12", "data", "homework")
files <- dir(path = CondPath,pattern = ".csv")

files 

homework<-data.frame(matrix(nrow = length(files), ncol = 5)) 
colnames(homework)<-c("filename","mean_temp","mean_light","sd_temp","sd_light") 

homework 

raw_data<-read_csv(paste0(CondPath,"/",files[1])) # test by reading 
head(raw_data)
mean_temp<-mean(raw_data$Temp.C, na.rm = TRUE) # calculate a mean
mean_temp

for (i in 1: length(files)){ #loop over 1:3 number of files
raw_data<-read_csv(paste0(CondPath,"/",files[i]))
glimpse(raw_data)

homework$filename[i]<-files[i]
homework$mean_temp[i]<-mean(raw_data$Temp.C, na.rm =TRUE)
homework$mean_light[i]<-mean(raw_data$Intensity.lux, na.rm =TRUE)
homework$sd_temp[i]<-sd(raw_data$Temp.C, na.rm =TRUE)
homework$sd_light[i]<-sd(raw_data$Intensity.lux, na.rm =TRUE)

}

homework
                            
```

```{r, purrdata}
CondPath<-here("Week_12", "data", "homework")
files <- dir(path = CondPath,pattern = ".csv", full.names = TRUE)
files 

purhw<-files %>%
  set_names()%>% # set's the id of each list to the file name
  map_df(read_csv,.id = "filename") %>% # map everything to a dataframe and put the id in a column called filename
  group_by(filename) %>%
  summarise(mean_temp = mean(Temp.C, na.rm = TRUE),
            mean_light = mean(Intensity.lux,na.rm = TRUE), 
            sd_temp = sd(Temp.C, na.rm = TRUE), 
            sd_light = sd(Intensity.lux, na.rm = TRUE))

purhw

```

